# Generated by Django 5.1.2 on 2024-10-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_App', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
